const GUIDES = [
{id:"priorita",cat:"base",ico:"\u23F1",title:"Priorita: regola del 3",tag:"INIZIA DA QUI",level:"info",blurb:"Cosa ti uccide prima. Serve per non sbagliare l'ordine.",
body:'<div class="okbox">In emergenza fai prima STOP: Stop, Think, Observe, Plan. Non correre a caso.</div><ul class="steps"><li><b>3 minuti</b> senza aria (o con emorragia arteriosa). Vie aeree e sanguinamento grave vengono prima di tutto.</li><li><b>3 ore</b> senza riparo in freddo, vento, pioggia o caldo estremo. L\'esposizione uccide prima della sete.</li><li><b>3 giorni</b> senza acqua. In caldo o con sforzo anche meno.</li><li><b>3 settimane</b> senza cibo. La fame non e la priorita immediata.</li></ul><p>Ordine pratico: 1) sicurezza della scena 2) ferite che uccidono 3) riparo e calore 4) segnalazione 5) acqua 6) cibo.</p>'},
{id:"112",cat:"emergenza",ico:"\uD83D\uDCDE",title:"Chiamare aiuto in Italia",tag:"CRITICO",level:"crit",blurb:"Cosa dire al 112 e cosa fare se non c'e segnale.",
body:'<div class="redbox">Se hai anche solo una barra di rete: chiama il <b>112</b>. In montagna, se hai dati, usa anche <b>GeoResQ</b> del Soccorso Alpino. Questa app non sostituisce i soccorsi.</div><h3>Cosa dire, in quest\'ordine</h3><ul class="steps"><li>Dove sei: localita, sentiero, rifugio, km strada, coordinate GPS.</li><li>Cosa e successo e quanti feriti.</li><li>Stato: respira? sanguina? cosciente?</li><li>Condizioni meteo e accesso (bosco, parete, neve).</li><li>Tuo numero e se la batteria sta finendo.</li></ul><p>Numeri: <b>112</b> unico \u00b7 <b>118</b> sanitario \u00b7 <b>115</b> Vigili del Fuoco \u00b7 <b>1530</b> Guardia Costiera.</p><h3>Senza segnale</h3><p>Sali di quota o spostati in cresta. Un SMS a volte passa dove la voce no. iPhone 14+ e alcuni Android hanno SOS via satellite. Risparmia batteria: modalita aereo + GPS a scatti.</p>'},
{id:"rcp",cat:"primo",ico:"\u2764\uFE0F",title:"Persona che non respira (RCP)",tag:"CRITICO",level:"crit",blurb:"Massaggio cardiaco se non respira e non reagisce.",
body:'<div class="redbox">Guida di supporto, non corso BLSD. Chiama 112 e metti lo speaker. Un DAE batte qualsiasi tecnica.</div><ul class="steps"><li>Sicurezza: niente traffico, cavi, fuoco, pendio instabile.</li><li>Scuoti le spalle e chiama forte. Se non risponde, apri le vie aeree (testa indietro, mento su).</li><li>Guarda, ascolta e senti il respiro per max 10 secondi. Respiro agonico (gasping) = non respira.</li><li>Manda qualcuno al 112 e a cercare un DAE. Se sei solo, chiama e poi inizia.</li><li>Compresioni al centro del petto, 5-6 cm, 100-120 al minuto. Braccia tese. Lascia risalire il torace.</li><li>Se sai fare le ventilazioni: 30 compressioni e 2 soffi. Altrimenti solo compressioni continue.</li><li>Non fermarti finche non arriva il DAE, i soccorsi, o la persona riprende a respirare.</li></ul><p>Neonati e bambini: tecnica diversa. Se non sei addestrato, comprimi comunque.</p>'},
{id:"emorragia",cat:"primo",ico:"\uD83E\uDE78",title:"Emorragia grave",tag:"CRITICO",level:"crit",blurb:"Sangue che zampilla o impregna i vestiti in pochi secondi.",
body:'<ul class="steps"><li>Proteggi te stesso se puoi (guanti, sacchetto, tessuto).</li><li>Scopri la ferita. Pressione diretta ferma e continua. Non alzare ogni due secondi per guardare.</li><li>Se il panno si satura, mettine un altro SOPRA. Non togliere il primo.</li><li>Arto: alza sopra il cuore se non sospetti frattura grave.</li><li>Se il sangue esce a fiotti e la pressione non basta: laccio 5-7 cm sopra la ferita (non sull\'articolazione). Stringi finche si ferma. Annota l\'ora.</li><li>Laccio improvvisato: cintura + bastone da girare. E doloroso se e efficace. Non usarlo per tagli banali.</li></ul><div class="warnbox">Un laccio lasciato ore puo costare l\'arto: e per salvare la vita quando stai perdendo troppo sangue.</div>'},
{id:"soffocamento",cat:"primo",ico:"\uD83D\uDE2E",title:"Soffocamento",tag:"CRITICO",level:"crit",blurb:"Non parla, non tossisce, porta le mani alla gola.",
body:'<ul class="steps"><li>Se tossisce forte e parla: incoraggia a tossire.</li><li>Se non passa aria: 5 colpi interscapolari, dal basso verso l\'alto, persona piegata in avanti.</li><li>Poi 5 compressioni addominali (Heimlich): pugno sopra l\'ombelico, tirate verso di te e in su.</li><li>Alterna 5 e 5 finche l\'oggetto esce o la persona collassa.</li><li>Se collassa: a terra e RCP. Togli l\'oggetto solo se lo vedi chiaro.</li></ul><p>Incinta o obeso: compressioni al petto. Lattante: 5 colpi sulla schiena a pancia in giu, poi 5 compressioni con due dita sul petto.</p>'},
{id:"shock-ipo",cat:"primo",ico:"\uD83E\uDD76",title:"Ipotermia e congelamento",tag:"URGENTE",level:"warn",blurb:"Brividi, confusione, sonnolenza, labbra blu.",
body:'<ul class="steps"><li>Togli dal vento e dall\'umido. Isola dal suolo (zaino, rami, giacca sotto).</li><li>Togli vestiti bagnati. Asciutto + strati + cappello + collo.</li><li>Riscalda il tronco: ascelle, inguine, petto. Non strofinare le estremita congelate.</li><li>Bevande zuccherate tiepide se e cosciente. Niente alcol.</li><li>Ipotermia grave (niente brividi, parla a vanvera): maneggia con delicatezza, orizzontale, chiama soccorsi.</li></ul><p>Congelamento: pelle bianca, insensibile. Non fuoco diretto. Acqua tiepida 37-39C solo se non rischia di ricongelare.</p>'},
{id:"caldo",cat:"primo",ico:"\uD83E\uDD75",title:"Colpo di calore e disidratazione",tag:"URGENTE",level:"warn",blurb:"Pelle calda, cessano i sudori, confusione, svenimento.",
body:'<div class="redbox">Colpo di calore = emergenza. Raffredda subito e chiama 112.</div><ul class="steps"><li>Ombra, sdraiato, togli strati inutili.</li><li>Bagna vestiti, ventila, freddo su collo, ascelle, inguine.</li><li>Se e cosciente e non vomita: sorsi d\'acqua. Meglio 1 L + 6 cucchiaini zucchero + mezzo di sale.</li><li>Non far bere se e assente o convulsivo.</li></ul>'},
{id:"fratture",cat:"primo",ico:"\uD83E\uDDB4",title:"Fratture, lussazioni, traumi",tag:"URGENTE",level:"warn",blurb:"Non riallineare. Immobilizza e tratta lo shock.",
body:'<ul class="steps"><li>Non rimettere a posto un osso. Immobilizza come sta, sopra e sotto l\'articolazione.</li><li>Stecca: ramo, bastone da trekking, giornale arrotolato, sciarpa.</li><li>Ferita aperta sull\'osso: copri pulito, non spingere frammenti.</li><li>Caduta dall\'alto o trauma al collo: non muovere il collo.</li><li>Shock: pallido, sudato. Sdraialo, tieni caldo, parla calmo.</li></ul>'},
{id:"ustioni",cat:"primo",ico:"\uD83D\uDD25",title:"Ustioni e fumo",tag:"URGENTE",level:"warn",blurb:"Acqua corrente tiepida, niente dentifricio o olio.",
body:'<ul class="steps"><li>Allontana la fonte. Vestiti che bruciano: terra, rotola, copri.</li><li>Raffredda 20 minuti con acqua pulita tiepida (non ghiaccio a contatto).</li><li>Togli anelli prima che gonfi. Non staccare tessuti incollati.</li><li>Copri con panno pulito umido o pellicola non stretta.</li><li>Ustione vasta, viso, vie aeree, elettrica, chimica: 112.</li></ul><p>Fumo: striscia basso, panno umido su naso e bocca. Non tornare dentro per oggetti.</p>'},
{id:"morsi",cat:"primo",ico:"\uD83D\uDC0D",title:"Morsi, punture, zecche",tag:"ATTENZIONE",level:"warn",blurb:"Italia: vipera, calabroni, zecche, processonaria.",
body:'<h3>Vipera</h3><p>Due fori, dolore, gonfiore. Non succhiare, non tagliare, non laccio stretto, non ghiaccio diretto. Immobilizza l\'arto piu basso del cuore, togli anelli, 112. Resta calmo.</p><h3>Ape / calabrone</h3><p>Togli il pungiglione raschiando. Ghiaccio. Gonfiore in gola, fischio, svenimento: 112. Penna di adrenalina nella coscia se ce l\'ha.</p><h3>Zecca</h3><p>Pinzetta a punta, tira dritto senza schiacciare. Disinfetta. Segna la data. Alone rosso che si allarga o febbre: medico.</p><h3>Processonaria</h3><p>Non toccare nidi e peli. Lava. Occhi e respiro = pronto soccorso.</p>'},
{id:"acqua",cat:"vita",ico:"\uD83D\uDCA7",title:"Trovare e rendere potabile l\'acqua",tag:"BASE",level:"info",blurb:"Meglio sete un\'ora in piu che un\'acqua che ti stende.",
body:'<ul class="steps"><li>Cerca: fondovalle, intaglio umido, rugiada all\'alba, ruscelli a monte dei pascoli.</li><li>Evita stagni verdi, carcasse, scarichi, miniere.</li><li>Filtra i solidi: maglia, calzino.</li><li>Bolli 1 minuto a rullare (3 minuti in alta quota).</li><li>Pastiglie: rispetta il tempo di contatto.</li></ul><div class="warnbox">Urina, acqua di mare e alcol non idratano.</div>'},
{id:"fuoco",cat:"vita",ico:"\uD83D\uDD25",title:"Accendere un fuoco",tag:"BASE",level:"info",blurb:"Calore, acqua bollita, segnale, morale.",
body:'<ul class="steps"><li>Sito riparato, terra nuda, lontano da rami e foglie. In estate molti boschi hanno divieto fuochi.</li><li>Prepara TUTTO prima: esca, ramoscelli, legna a dito, poi a polso.</li><li>Struttura a tegola o teepee. Lascia entrare aria.</li><li>Accendino, fiammiferi, acciarino. Bagnato: legno morto in piedi, cuore secco, resina, betulla.</li></ul><p>Spegni con acqua fino a poter toccare la cenere.</p>'},
{id:"riparo",cat:"vita",ico:"\u26FA",title:"Riparo e isolamento",tag:"BASE",level:"info",blurb:"Prima il suolo, poi il vento, poi la pioggia.",
body:'<ul class="steps"><li>Non dormire sulla terra nuda. Isola con zaino, fronde, giacca.</li><li>Sito alto rispetto all\'acqua, non sotto alberi morti.</li><li>Telo: corda tra due alberi, tetto, lati bassi sopravento.</li><li>Senza telo: lean-to su un tronco, foglie come coperta.</li><li>Neve: trincea o buca sottovento. Niente fuoco in riparo chiuso.</li></ul>'},
{id:"cibo",cat:"vita",ico:"\uD83C\uDF53",title:"Cibo: cosa non fare",tag:"ATTENZIONE",level:"warn",blurb:"In 72 ore il cibo e secondario. Le piante sbagliate no.",
body:'<div class="redbox">Non mangiare una pianta se non la riconosci al 100%.</div><p>In Italia, con cautela: mora, lampone, mirtillo, castagna cotta, noce, nocciola, tarassaco giovane. Evita i funghi se non sei micologo.</p><p>Tossiche da non confondere: mughetto, belladonna, colchico, tasso, digitale, cicuta, vischio.</p>'},
{id:"orientamento",cat:"nav",ico:"\uD83E\uDDED",title:"Orientamento senza rete",tag:"BASE",level:"info",blurb:"Il GPS del telefono spesso funziona anche offline.",
body:'<p>Il chip GPS non usa la rete cellulare. La rete serve alle mappe online. Scarica prima Organic Maps o OsmAnd della zona.</p><ul class="steps"><li>Sole: a mezzogiorno solare in Italia sta a sud.</li><li>Ombra-bastone: due tacche a 15 minuti. La linea e est-ovest (prima marca = ovest).</li><li>Notte: le due stelle del mestolo dell\'Orsa Maggiore puntano Polaris (nord).</li><li>Il muschio sempre a nord e inaffidabile.</li><li>Perso: non scendere a caso in un canalone. Riparo e segnale.</li></ul>'},
{id:"segnali",cat:"nav",ico:"\uD83D\uDEA8",title:"Farsi trovare",tag:"CRITICO",level:"crit",blurb:"Tre segnali = disagio. Resta visibile e fermo se puoi.",
body:'<ul class="steps"><li>Fischietto: 3 fischi lunghi, pausa, ripeti.</li><li>Luce: 3 lampi. In app c\'e il lampeggio dello schermo.</li><li>Specchio o schermo verso aereo: lampi brevi.</li><li>A terra: V = aiuto, X = bisogno medico, freccia = direzione.</li><li>Resta vicino all\'ultimo punto noto (auto, sentiero, rifugio).</li></ul>'},
{id:"montagna",cat:"scenario",ico:"\u26F0\uFE0F",title:"Perso o infortunato in montagna",tag:"SCENARIO",level:"warn",blurb:"Alpi, Appennini, anche colline facili.",
body:'<ul class="steps"><li>Stop. Bevi, metti il piumino prima di sentire freddo, guarda GPS.</li><li>Se hai segnale: 112 e GeoResQ. Dai quota, sentiero CAI, ultimo bivio.</li><li>Senza segnale: dosso aperto, SMS, SOS satellite se c\'e.</li><li>Buio e via ignota: riparo e segnale. La discesa notturna fa piu danni della notte ferma.</li><li>Temporale: giu dalle creste, lontano da alberi isolati, accucciato sullo zaino.</li></ul>'},
{id:"bosco",cat:"scenario",ico:"\uD83C\uDF32",title:"Bosco e notte all\'aperto",tag:"SCENARIO",level:"info",blurb:"Perdersi a 3 km da una strada e piu comune di quanto pensi.",
body:'<p>Segui una linea sicura: sentiero, recinzione, torrente, rumore di auto. Segna i bivi con un rametto-freccia.</p><p>Cinghiali: non avvicinare i piccoli, ritirati piano. Orso: parla, non correre, non frapporsi ai cuccioli. Lupo: resta in gruppo, non scappare di spalle.</p>'},
{id:"mare",cat:"scenario",ico:"\uD83C\uDF0A",title:"Mare, fiume, alluvione",tag:"SCENARIO",level:"crit",blurb:"Correnti, ipotermia da acqua, sottopassaggi.",
body:'<p><b>Corrente</b>: non nuotare contro. Poi taglia in diagonale verso riva. Rip current: nuota parallelo alla spiaggia.</p><p><b>Alluvione</b>: sali. Non attraversare sottopassi o strade con acqua in movimento. 20 cm muovono un\'auto. Acqua di piena = non potabile.</p>'},
{id:"terremoto",cat:"scenario",ico:"\uD83C\uDFDA\uFE0F",title:"Terremoto",tag:"SCENARIO",level:"crit",blurb:"Drop, Cover, Hold. Poi gas e uscite.",
body:'<ul class="steps"><li>Dentro: sotto un tavolo robusto o lungo un muro portante, testa coperta. Lontano dai vetri.</li><li>Fuori: lontano da gronde, vetri, fili.</li><li>In auto: ferma lontano da ponti, resta dentro finche cessa.</li><li>Dopo: chiudi il gas se senti odore, niente fiamme, scarpe ai piedi.</li></ul>'},
{id:"blackout",cat:"scenario",ico:"\uD83D\uDD6F",title:"Blackout e casa isolata",tag:"SCENARIO",level:"info",blurb:"Freddo, cibo, farmaci, vicini.",
body:'<p>Una stanza sola da scaldare. Apri il frigo il meno possibile.</p><p>Mai generatore, barbecue o braciere in casa o garage: il monossido non si sente.</p><p>Power bank e radio a pile. Piano con i vicini per chi ha ossigeno o insulina.</p>'},
{id:"auto",cat:"scenario",ico:"\uD83D\uDE97",title:"Incidente o auto bloccata",tag:"SCENARIO",level:"warn",blurb:"Nella macchina hai gia riparo, metallo, segnale.",
body:'<ul class="steps"><li>Giubbotto, triangolo, luci. Fumo o incendio: fuori e via dal ciglio.</li><li>Non estrarre feriti se sospetti trauma midollare, salvo incendio o annegamento.</li><li>Neve su strada battuta: resta in auto. Scarico libero dalla neve. Motore a intermittenza, finestrino a fessura.</li></ul>'}
];

const KITS = {
  tasca: ["Fischietto senza pallina","Accendino + acciarino","Mini-torcia o frontale","Coperta isotermica","Cerotti, garza, bendaggio","Laccio emostatico o cintura dedicata","Pastiglie per l'acqua","Nastro americano + paracord","Coltello o multi-tool","Sacco-bidone o telo","Farmaci personali","Power bank carico"],
  giorno: ["Tutto il kit tasca","1,5-2 L acqua + filtro o pentolino","Piumino / guscio","Berretto e guanti anche d'estate in quota","Mappa offline gia scaricata","Cibo 24 h","Frontale con batterie nuove","Telo 3x3 o poncho","Crema solare e occhiali"],
  casa: ["9 L acqua a persona (3 giorni)","Cibo a lunga scadenza + apriscatole","Radio a pile","Torchie e pile","Kit primo soccorso vero","Farmaci per 7 giorni","Contanti piccoli","Copie documenti","Caricabatterie da auto + power bank","Sapere dove sono gas e quadro elettrico","Punto di ritrovo famiglia"]
};

const HOME_ACTIONS = [
  {id:"112",ico:"\uD83D\uDCDE",title:"Aiuto e 112",text:"Cosa dire e cosa fare senza segnale"},
  {id:"rcp",ico:"\u2764\uFE0F",title:"Non respira",text:"RCP passo passo"},
  {id:"emorragia",ico:"\uD83E\uDE78",title:"Sangue",text:"Pressione e laccio"},
  {id:"priorita",ico:"\u23F1",title:"Priorita",text:"Regola del 3 e STOP"}
];
